name: Using Ponca as submodule

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl.exe", cxx: "cl.exe", installEigen: 'ON'}
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", installEigen: 'ON'}
          - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++", installEigen: 'ON'}
          - { name: "Windows MSVC", os: windows-latest, cc: "cl.exe", cxx: "cl.exe", installEigen: 'OFF'}
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", installEigen: 'OFF'}
          - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++", installEigen: 'OFF'}
    steps:
      - name: Checkout Eigen repository (master branch)
        run: git clone https://gitlab.com/libeigen/eigen.git eigen_src && mkdir eigen_installed/
        if: ${{ matrix.config.installEigen == 'ON'}}
      - name: Configure Eigen
        run: mkdir eigen_build && cd eigen_build && cmake ../eigen_src -DCMAKE_INSTALL_PREFIX=../eigen_installed
        if: ${{ matrix.config.installEigen == 'ON'}}
      - name: Install Eigen
        run:  cd eigen_build && cmake --build . --target install
        if: ${{ matrix.config.installEigen == 'ON'}}

      - name: Checkout helper repository with Ponca as submodule (master branch)
        run: git clone https://github.com/poncateam/ci-submodule-helper.git repo --recursive
      - name: Update ponca submodule to current PR
        run: cd repo/ponca && git fetch && git checkout ${{ github.head_ref }}
      - name: Configure cmake project with installed eigen
        run : mkdir build && cd build && cmake ../repo -DEigen3_DIR=../eigen_installed/share/eigen3/cmake/
        if: ${{ matrix.config.installEigen == 'ON'}}
      - name: Configure cmake project with local eigen
        run : mkdir build && cd build && cmake ../repo
        if: ${{ matrix.config.installEigen == 'OFF'}}
      - name: Build
        run : cd build && cmake --build .
